---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: apigw
  name: apigw
spec:
  ports:
    - name: "http"
      port: 8080
      targetPort: 8080
  selector:
    app: apigw
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: apigw
  name: apigw
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apigw
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: apigw
    spec:
      containers:
        - env:
            - name: VC_CONFIG_YAML
              value: config.yaml
          image: docker.sunet.se/dc4eu/apigw:latest
          name: apigw
          ports:
            - containerPort: 8080
              protocol: TCP          
          volumeMounts:
            - mountPath: /config.yaml
              name: config
              readOnly: true
              subPath: config.yaml
            - mountPath: /var/log/sunet
              name: apigw-volume
          imagePullPolicy: Always
      restartPolicy: Always
      volumes:
        - configMap:
            items:
              - key: config.yaml
                path: config.yaml
            name: config
          name: config
        - name: apigw-volume
          emptyDir: {}
