---
common:
  mongo:
    uri: mongodb://mongo:27017
  production: false
  tracing:
    addr: jaeger:4318
    type: jaeger
    #timeout: 10
  queues:
    simple_queue:
      vc_persistent_save:
        name: vc_persistent_save
      vc_persistent_get:
        name: vc_persistent_get
      vc_persistent_delete:
        name: vc_persistent_delete
      vc_persistent_replace:
        name: vc_persistent_replace
  key_value:
    db: 3
    addr: redis:6379
    password: test-password
  qr:
    base_url: "https://deutsche-rentenversicherung.de"
    recovery_level: 2
    size: 256
  kafka:
    enabled: true
    brokers:
      - "kafka0:9092"
      - "kafka1:9092"

authentic_sources:
  SUNET_v1:
    country_code: "SE"
    notification_endpoint:
      url: "http://vc_dev_apigw:8080/api/v1/document/notify"
    authentic_source_endpoint: 
      url: "http://vc_dev_apigw:8080"
    signature_service_endpoint: 
      url: "http://vc_dev_issuer:8080"
    revocation_service_endpoint: 
      url: "http://vc_dev_apigw:8080/api/v1/document/revok"
    credential_types:
      EHIC:
        profile: "SD-JWT"
      PDA1:
        profile: "SD-JWT"
  SUNET_v2:
    country_code: "SE"
    notification_endpoint:
      url: "http://vc_dev_apigw:8080/api/v1/document/notify"
    authentic_source_endpoint:
      url: "http://vc_dev_mockas:8080"
    signature_service_endpoint:
      url: "http://vc_dev_issuer:8080"
    revocation_service_endpoint:
      url: "http://vc_dev_apigw:8080/api/v1/document/revok"
    datastore_service_endpoint:
      url: "http://vc_dev_apigw:8080"
    credential_types:
      EHIC:
        profile: "SD-JWT"
      PDA1:
        profile: "SD-JWT"

issuer:
  identifier: "SUNET_v1"
  api_server:
    addr: :8080
  grpc_server:
    addr: vc_dev_issuer:8090
  signing_key_path: "/private_ec256.pem"
  jwt_attribute:
    issuer:  https://issuer.sunet.se
    enable_not_before: true
    valid_duration: 3600
    verifiable_credential_type: "https://credential.sunet.se/identity_credential"

verifier:
  api_server:
    addr: :8080
  grpc_server:
    addr: vc_dev_verifier:8090

registry:
  api_server:
    addr: :8080
  smt:
    update_periodicity: 5
    init_leaf: 575cea4a-5725-11ee-8287-2b486b7ace28
  grpc_server:
    addr: vc_dev_registry:8090

persistent:
  api_server:
    addr: :8080

apigw:
  identifier: "SUNET_v1"
  trust_model:
    type: "openid_federation"
    trust_anchors:
      - "https://example.com/trust_anchor.pem"
  api_server:
    addr: :8080
    basic_auth:
      enabled: false
      users:
        admin: "secret123"

mock_as:
  api_server:
    addr: :8080
  datastore_url: http://vc_dev_apigw:8080

ui:
  api_server:
    addr: :8080
  username: "admin"
  password: "secret123"
  #It is recommended to use an authentication key with 32 or 64 bytes.
  session_cookie_authentication_key: "PjanW5cOBIlWzjLK23Q8NIo4va53e1bsgWmcqMdznVzkW3uEozfotj7MZsD7HpBo"
  #The encryption key, must be either 16, 24, or 32 bytes to select AES-128, AES-192, or AES-256 modes.
  session_store_encryption_key: "SQxqb3LKw1YFyAiy4j7FaGGJKeEzr8Db"
  services:
    apigw:
      base_url: http://vc_dev_apigw:8080
    mockas:
      base_url: http://vc_dev_mockas:8080
