---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: issuer
  name: issuer
spec:
  ports:
    - name: "http"
      port: 8080
      targetPort: 8080
    - name: "grpc"
      port: 8090
      targetPort: 8090
  selector:
    app: issuer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: issuer
  name: issuer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: issuer
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: issuer
    spec:
      containers:
        - env:
            - name: VC_CONFIG_YAML
              value: config.yaml
          image: docker.sunet.se/dc4eu/issuer:latest
          name: vc-dev-issuer
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 8090
              protocol: TCP
          volumeMounts:
            - mountPath: /config.yaml
              name: config
              readOnly: true
              subPath: config.yaml
            - mountPath: /var/log/sunet
              name: issuer-log-volume
            - mountPath: /private_ec256.pem
              name: issuer-cert-volume
              readOnly: true
              subPath: private_ec256.pem
      restartPolicy: Always
      volumes:
        - configMap:
            items:
              - key: config.yaml
                path: config.yaml
            name: config
          name: config
        - name: issuer-log-volume
          emptyDir: {}
        - name: issuer-cert-volume
          secret:
            secretName: issuer-cert
            items:
              - key: private_ec256.pem
                path: private_ec256.pem
