apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: kafka0
  name: kafka0
spec:
  ports:
    - name: "9092"
      port: 9092
      targetPort: 9092
    - name: "9093"
      port: 9093
      targetPort: 9093
  selector:
    io.kompose.service: kafka0
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: kafka0-claim
  name: kafka0-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: kafka0
  name: kafka0
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: kafka0
  strategy:
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: kafka0
    spec:
      containers:
        - env:
            - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
              value: "true"
            - name: KAFKA_CFG_ADVERTISED_LISTENERS
              value: PLAINTEXT://kafka0:9092
            - name: KAFKA_CFG_CONTROLLER_LISTENER_NAMES
              value: CONTROLLER
            - name: KAFKA_CFG_CONTROLLER_QUORUM_VOTERS
              value: 0@kafka0:9093,1@kafka1:9093
            - name: KAFKA_CFG_DEFAULT_REPLICATION_FACTOR
              value: "2"
            - name: KAFKA_CFG_LISTENERS
              value: PLAINTEXT://:9092,CONTROLLER://:9093
            - name: KAFKA_CFG_NODE_ID
              value: "0"
            - name: KAFKA_CFG_NUM_PARTITIONS
              value: "2"
            - name: KAFKA_CFG_PROCESS_ROLES
              value: broker,controller
            - name: KAFKA_CLUSTERS_0_NAME
              value: vc_kafka_cluster
            - name: KAFKA_KRAFT_CLUSTER_ID
              value: 550e8400-e29b-42d4-a716-446655440000
          image: bitnami/kafka:latest
          name: vc-dev-kafka0
          ports:
            - containerPort: 9092
              protocol: TCP
            - containerPort: 9093
              protocol: TCP
          volumeMounts:
            - mountPath: /bitnami/kafka
              name: kafka0-volume
      restartPolicy: Always
      volumes:
        - name: kafka0-volume
          persistentVolumeClaim:
            claimName: kafka0-claim
