apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: kafka-ui
  name: kafka-ui
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    io.kompose.service: kafka-ui
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: kafka-ui
  name: kafka-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: kafka-ui
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: kafka-ui
    spec:
      containers:
        - env:
            - name: AUTH_TYPE
              value: LOGIN_FORM
            - name: DYNAMIC_CONFIG_ENABLED
              value: "true"
            - name: KAFKA_CLUSTERS_0_BOOTSTRAP_SERVERS
              value: kafka0:9092,kafka1:9092
            - name: KAFKA_CLUSTERS_0_NAME
              value: vc_kafka_cluster
            - name: KAFKA_UI_DEFAULT_OFFSET_SEARCH_STRATEGY
              value: LATEST
            - name: KAFKA_UI_MAX_RECORDS_PER_PAGE
              value: "500"
            - name: SPRING_SECURITY_USER_NAME
              value: admin
            - name: SPRING_SECURITY_USER_PASSWORD
              value: admin123
          image: provectuslabs/kafka-ui:latest
          name: vc-dev-kafka-ui
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always
