---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: persistent
  name: persistent
spec:
  ports:
    - name: "http"
      port: 8080
      targetPort: 8080
  selector:
    io.kompose.service: persistent
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: persistent
  name: persistent
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: persistent
  strategy:
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: persistent
    spec:
      containers:
        - env:
            - name: VC_CONFIG_YAML
              value: config.yaml
          image: docker.sunet.se/dc4eu/persistent:latest
          name: vc-dev-persistent
          ports:
            - containerPort: 8080
              protocol: TCP          
          volumeMounts:
            - mountPath: /config.yaml
              name: config
              readOnly: true
              subPath: config.yaml
      restartPolicy: Always
      volumes:
        - configMap:
            items:
              - key: config.yaml
                path: config.yaml
            name: persistent-cm
          name: config
