---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: persistent
  name: persistent
spec:
  ports:
    - name: "http"
      port: 8080
      targetPort: 8080
  selector:
    app: persistent
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: persistent
  name: persistent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: persistent
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: persistent
    spec:
      containers:
        - env:
            - name: VC_CONFIG_YAML
              value: config.yaml
          image: docker.sunet.se/dc4eu/persistent:latest
          name: vc-dev-persistent
          ports:
            - containerPort: 8080
              protocol: TCP          
          volumeMounts:
            - mountPath: /config.yaml
              name: config
              readOnly: true
              subPath: config.yaml
      restartPolicy: Always
      volumes:
        - configMap:
            items:
              - key: config.yaml
                path: config.yaml
            name: config
          name: config
