---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: registry
  name: registry
spec:
  ports:
    - name: "http"
      port: 8080
      targetPort: 8080
    - name: "grpc"
      port: 8090
      targetPort: 8090
  selector:
    app: registry
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: registry
  name: registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registry
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: registry
    spec:
      containers:
        - env:
            - name: VC_CONFIG_YAML
              value: config.yaml
          image: docker.sunet.se/dc4eu/registry:latest
          name: vc-dev-registry
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 8090
              protocol: TCP
          volumeMounts:
            - mountPath: /config.yaml
              name: config
              readOnly: true
              subPath: config.yaml
      restartPolicy: Always
      volumes:
        - configMap:
            items:
              - key: config.yaml
                path: config.yaml
            name: config
          name: config
