---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ui
  name: ui
spec:
  ports:
    - name: "http"
      port: 8080
      targetPort: 8080
  selector:
    app: ui
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ui
  name: ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ui
    spec:
      containers:
        - env:
            - name: VC_CONFIG_YAML
              value: config.yaml
          image: docker.sunet.se/dc4eu/ui:latest
          name: ui
          ports:
            - containerPort: 8080
              protocol: TCP
          volumeMounts:
            - mountPath: /config.yaml
              name: config
              readOnly: true
              subPath: config.yaml
          imagePullPolicy: Always
      restartPolicy: Always
      volumes:
        - configMap:
            items:
              - key: config.yaml
                path: config.yaml
            name: config
          name: config
