apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: verifier-claim
  name: verifier-claim
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 100Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: verifier
  name: verifier
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: verifier
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: verifier
    spec:
      containers:
        - env:
            - name: VC_CONFIG_YAML
              value: config.yaml
          image: docker.sunet.se/dc4eu/verifier:latest
          name: vc-dev-verifier
          volumeMounts:
            - mountPath: /cert
              name: verifier-volume
              readOnly: true
            - mountPath: /config.yaml
              name: config
              readOnly: true
              subPath: config.yaml
      restartPolicy: Always
      volumes:
        - name: verifier-volume
          persistentVolumeClaim:
            claimName: verifier-claim
            readOnly: true
        - configMap:
            items:
              - key: config.yaml
                path: config.yaml
            name: verifier-cm
          name: config
