---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: verifier
  name: verifier
spec:
  ports:
    - name: "http"
      port: 8080
      targetPort: 8080
    - name: "grpc"
      port: 8090
      targetPort: 8090
  selector:
    app: verifier
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: verifier
  name: verifier
spec:
  replicas: 1
  selector:
    matchLabels:
      app: verifier
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: verifier
    spec:
      containers:
        - env:
            - name: VC_CONFIG_YAML
              value: config.yaml
          image: docker.sunet.se/dc4eu/verifier:latest
          name: verifier
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 8090
              protocol: TCP
          volumeMounts:
            - mountPath: /cert
              name: verifier-cert-volume
              readOnly: true
            - mountPath: /config.yaml
              name: config
              readOnly: true
              subPath: config.yaml
      restartPolicy: Always
      volumes:
        - configMap:
            items:
              - key: config.yaml
                path: config.yaml
            name: config
          name: config
        - name: verifier-cert-volume
          emptyDir: {}
          # secret:
          #   secretName: verifier-cert
